#!/usr/bin/env python3
"""
Generate migration script to update printer_model image URLs to Supabase format.
This script maps printer models to actual image files and generates SQL UPDATE statements.
"""

import os
import yaml
import json
from pathlib import Path

# Configuration
script_dir = os.path.dirname(os.path.abspath(__file__))
SPEC_FILE_PATH = os.path.join(script_dir, "specs.yaml")
PRINTER_PICS_FOLDER = os.path.join(script_dir, "..", "..", "assets", "printer_pics")
OUTPUT_MIGRATION_FILE = os.path.join(script_dir, "..", "..", "database", "migrations", "10_MIGRATION_UPDATE_PRINTER_MODEL_IMAGES_TO_SUPABASE.sql")

SUPABASE_BASE_URL = "https://ilzhoxyiftrpphhbwliz.supabase.co/storage/v1/object/public"
SUPABASE_BUCKET_PRINTER_MODEL_IMAGES = "printer_model_images"

def load_spec(spec_path):
    """Load the specification YAML file."""
    with open(spec_path, 'r', encoding='utf-8') as f:
        spec = yaml.safe_load(f)
    return spec

def get_printer_image_files():
    """Get list of image files from printer_pics folder."""
    if not os.path.exists(PRINTER_PICS_FOLDER):
        print(f"Warning: Folder {PRINTER_PICS_FOLDER} does not exist")
        return []
    
    image_files = []
    for file in os.listdir(PRINTER_PICS_FOLDER):
        if os.path.isfile(os.path.join(PRINTER_PICS_FOLDER, file)):
            ext = os.path.splitext(file)[1].lower()
            if ext in ['.jpg', '.jpeg', '.png', '.webp']:
                image_files.append(file)
    
    return sorted(image_files)

def find_matching_image(model_name, brand_name, image_files):
    """
    Find matching image file for a printer model.
    Returns the filename if found, None otherwise.
    """
    model_lower = model_name.lower()
    brand_lower = brand_name.lower()
    
    # Extract keywords from model name
    model_keywords = model_lower.replace('-', ' ').replace('_', ' ').replace('/', ' ').split()
    model_keywords = [kw for kw in model_keywords if len(kw) > 2]  # Filter short words
    
    # Try exact or partial match
    for img_file in image_files:
        img_lower = img_file.lower()
        
        # Check if model keywords appear in image filename
        if any(keyword in img_lower for keyword in model_keywords):
            return img_file
        
        # Check if brand name appears in image filename
        if brand_lower in img_lower:
            return img_file
    
    return None

def generate_supabase_url(filename):
    """Generate Supabase URL for an image file."""
    return f"{SUPABASE_BASE_URL}/{SUPABASE_BUCKET_PRINTER_MODEL_IMAGES}/{filename}"

def generate_migration_script():
    """Generate the migration SQL script."""
    
    # Load specs
    spec = load_spec(SPEC_FILE_PATH)
    printer_brands = spec.get('printer_brands', [])
    
    # Get available image files
    image_files = get_printer_image_files()
    print(f"Found {len(image_files)} image files in {PRINTER_PICS_FOLDER}")
    print(f"Image files: {', '.join(image_files[:5])}{'...' if len(image_files) > 5 else ''}")
    
    # Build model to image mapping
    model_image_mapping = {}
    unmapped_models = []
    
    for brand_config in printer_brands:
        brand_name = brand_config['name']
        for model_config in brand_config.get('models', []):
            model_name = model_config['name']
            full_model_name = f"{brand_name} {model_name}"
            
            # Try to find matching image
            matching_image = find_matching_image(model_name, brand_name, image_files)
            
            if matching_image:
                supabase_url = generate_supabase_url(matching_image)
                model_image_mapping[full_model_name] = {
                    'brand': brand_name,
                    'model': model_name,
                    'image_file': matching_image,
                    'supabase_url': supabase_url
                }
                print(f"✓ Mapped: {full_model_name} -> {matching_image}")
            else:
                unmapped_models.append(full_model_name)
                print(f"✗ No match: {full_model_name}")
    
    # Generate SQL migration script
    sql_lines = []
    sql_lines.append("-- ============================================")
    sql_lines.append("-- MIGRATION: Update printer_model image URLs to Supabase storage format")
    sql_lines.append("-- ============================================")
    sql_lines.append("-- Date: 2025-01-XX")
    sql_lines.append("-- Description: ")
    sql_lines.append("--  Updates image_2d_url in printer_model table to use Supabase storage URLs")
    sql_lines.append("--  Format: https://ilzhoxyiftrpphhbwliz.supabase.co/storage/v1/object/public/printer_model_images/<filename>")
    sql_lines.append("-- ")
    sql_lines.append(f"-- Generated by: generate_printer_image_migration.py")
    sql_lines.append(f"-- Total models mapped: {len(model_image_mapping)}")
    sql_lines.append(f"-- Unmapped models: {len(unmapped_models)}")
    sql_lines.append("-- ============================================")
    sql_lines.append("")
    sql_lines.append("USE printing_service_db;")
    sql_lines.append("GO")
    sql_lines.append("")
    
    # Generate UPDATE statements for each mapped model
    if model_image_mapping:
        sql_lines.append("-- Step 1: Update image_2d_url for mapped printer models")
        sql_lines.append("")
        
        for full_name, mapping in model_image_mapping.items():
            brand_name = mapping['brand']
            model_name = mapping['model']
            supabase_url = mapping['supabase_url']
            image_file = mapping['image_file']
            
            # Escape single quotes in SQL
            brand_name_escaped = brand_name.replace("'", "''")
            model_name_escaped = model_name.replace("'", "''")
            supabase_url_escaped = supabase_url.replace("'", "''")
            
            sql_lines.append(f"-- {brand_name} {model_name} -> {image_file}")
            sql_lines.append(f"UPDATE printer_model")
            sql_lines.append(f"SET image_2d_url = '{supabase_url_escaped}'")
            sql_lines.append(f"WHERE model_id IN (")
            sql_lines.append(f"    SELECT pm.model_id")
            sql_lines.append(f"    FROM printer_model pm")
            sql_lines.append(f"    INNER JOIN brand b ON pm.brand_id = b.brand_id")
            sql_lines.append(f"    WHERE b.brand_name = '{brand_name_escaped}'")
            sql_lines.append(f"      AND pm.model_name = '{model_name_escaped}'")
            sql_lines.append(f");")
            sql_lines.append("GO")
            sql_lines.append("")
    
    # Add note about unmapped models
    if unmapped_models:
        sql_lines.append("-- ============================================")
        sql_lines.append("-- NOTE: The following models were not mapped to images:")
        for model in unmapped_models:
            sql_lines.append(f"--   - {model}")
        sql_lines.append("-- ============================================")
        sql_lines.append("")
    
    # Add verification query
    sql_lines.append("-- Step 2: Verify the changes")
    sql_lines.append("-- Uncomment the following to verify:")
    sql_lines.append("-- SELECT TOP 20")
    sql_lines.append("--     pm.model_id,")
    sql_lines.append("--     b.brand_name,")
    sql_lines.append("--     pm.model_name,")
    sql_lines.append("--     pm.image_2d_url,")
    sql_lines.append("--     pm.image_3d_url")
    sql_lines.append("-- FROM printer_model pm")
    sql_lines.append("-- JOIN brand b ON pm.brand_id = b.brand_id")
    sql_lines.append("-- WHERE pm.image_2d_url IS NOT NULL")
    sql_lines.append("-- ORDER BY b.brand_name, pm.model_name;")
    sql_lines.append("-- GO")
    sql_lines.append("")
    sql_lines.append("-- ============================================")
    sql_lines.append("-- Migration completed successfully")
    sql_lines.append("-- ============================================")
    sql_lines.append("-- Note: This migration updates existing URLs. For new data generation,")
    sql_lines.append("-- use the updated generate.py script which automatically generates Supabase URLs.")
    sql_lines.append("")
    
    return '\n'.join(sql_lines), model_image_mapping, unmapped_models

def main():
    """Main function."""
    print("=" * 70)
    print("Printer Image Migration Script Generator")
    print("=" * 70)
    print()
    
    # Generate migration script
    sql_content, mappings, unmapped = generate_migration_script()
    
    # Write to file
    os.makedirs(os.path.dirname(OUTPUT_MIGRATION_FILE), exist_ok=True)
    with open(OUTPUT_MIGRATION_FILE, 'w', encoding='utf-8') as f:
        f.write(sql_content)
    
    print()
    print("=" * 70)
    print(f"✓ Migration script generated: {OUTPUT_MIGRATION_FILE}")
    print(f"  - Mapped models: {len(mappings)}")
    print(f"  - Unmapped models: {len(unmapped)}")
    print("=" * 70)
    print()
    
    # Print summary
    if mappings:
        print("Mapped Models:")
        for full_name, mapping in mappings.items():
            print(f"  {full_name:50} -> {mapping['image_file']}")
        print()
    
    if unmapped:
        print("Unmapped Models (no image found):")
        for model in unmapped:
            print(f"  - {model}")
        print()
    
    # Verify output
    print("Verifying generated SQL...")
    print("-" * 70)
    
    # Check if file was created
    if os.path.exists(OUTPUT_MIGRATION_FILE):
        file_size = os.path.getsize(OUTPUT_MIGRATION_FILE)
        print(f"✓ File created: {file_size} bytes")
        
        # Count SQL statements
        update_count = sql_content.count("UPDATE printer_model")
        go_count = sql_content.count("GO")
        print(f"✓ Contains {update_count} UPDATE statements")
        print(f"✓ Contains {go_count} GO statements")
        
        # Show first few lines
        print("\nFirst 20 lines of generated SQL:")
        print("-" * 70)
        lines = sql_content.split('\n')[:20]
        for i, line in enumerate(lines, 1):
            print(f"{i:3}: {line}")
        
        if len(sql_content.split('\n')) > 20:
            print(f"... ({len(sql_content.split('\n')) - 20} more lines)")
        
        print("-" * 70)
        print("✓ Migration script verification complete!")
    else:
        print("✗ ERROR: File was not created!")
        return 1
    
    return 0

if __name__ == "__main__":
    exit(main())

