-- ============================================
-- MIGRATION: Update printer_model image URLs to Supabase storage format
-- ============================================
-- Date: 2025-01-XX
-- Description: 
--  Updates image_2d_url in printer_model table to use Supabase storage URLs
--  Format: https://ilzhoxyiftrpphhbwliz.supabase.co/storage/v1/object/public/printer_model_images/<filename>
-- 
-- Generated by: generate_printer_image_migration.py
-- Total models mapped: 5
-- Unmapped models: 9
-- ============================================

USE printing_service_db;
GO

-- Step 1: Update image_2d_url for mapped printer models

-- HP Color LaserJet Pro M454dw -> epson-colore-printer-inkjet.jpg
UPDATE printer_model
SET image_2d_url = 'https://ilzhoxyiftrpphhbwliz.supabase.co/storage/v1/object/public/printer_model_images/epson-colore-printer-inkjet.jpg'
WHERE model_id IN (
    SELECT pm.model_id
    FROM printer_model pm
    INNER JOIN brand b ON pm.brand_id = b.brand_id
    WHERE b.brand_name = 'HP'
      AND pm.model_name = 'Color LaserJet Pro M454dw'
);
GO

-- Canon Color imageCLASS MF644Cdw -> epson-colore-printer-inkjet.jpg
UPDATE printer_model
SET image_2d_url = 'https://ilzhoxyiftrpphhbwliz.supabase.co/storage/v1/object/public/printer_model_images/epson-colore-printer-inkjet.jpg'
WHERE model_id IN (
    SELECT pm.model_id
    FROM printer_model pm
    INNER JOIN brand b ON pm.brand_id = b.brand_id
    WHERE b.brand_name = 'Canon'
      AND pm.model_name = 'Color imageCLASS MF644Cdw'
);
GO

-- Epson WorkForce Pro WF-3720 -> Epson-EcoTank-L3210-A4-All-in-One-Ink-Tank-Printer-1.jpg
UPDATE printer_model
SET image_2d_url = 'https://ilzhoxyiftrpphhbwliz.supabase.co/storage/v1/object/public/printer_model_images/Epson-EcoTank-L3210-A4-All-in-One-Ink-Tank-Printer-1.jpg'
WHERE model_id IN (
    SELECT pm.model_id
    FROM printer_model pm
    INNER JOIN brand b ON pm.brand_id = b.brand_id
    WHERE b.brand_name = 'Epson'
      AND pm.model_name = 'WorkForce Pro WF-3720'
);
GO

-- Epson EcoTank L3550 -> Epson-EcoTank-L3210-A4-All-in-One-Ink-Tank-Printer-1.jpg
UPDATE printer_model
SET image_2d_url = 'https://ilzhoxyiftrpphhbwliz.supabase.co/storage/v1/object/public/printer_model_images/Epson-EcoTank-L3210-A4-All-in-One-Ink-Tank-Printer-1.jpg'
WHERE model_id IN (
    SELECT pm.model_id
    FROM printer_model pm
    INNER JOIN brand b ON pm.brand_id = b.brand_id
    WHERE b.brand_name = 'Epson'
      AND pm.model_name = 'EcoTank L3550'
);
GO

-- Epson SureColor P400 -> Epson-EcoTank-L3210-A4-All-in-One-Ink-Tank-Printer-1.jpg
UPDATE printer_model
SET image_2d_url = 'https://ilzhoxyiftrpphhbwliz.supabase.co/storage/v1/object/public/printer_model_images/Epson-EcoTank-L3210-A4-All-in-One-Ink-Tank-Printer-1.jpg'
WHERE model_id IN (
    SELECT pm.model_id
    FROM printer_model pm
    INNER JOIN brand b ON pm.brand_id = b.brand_id
    WHERE b.brand_name = 'Epson'
      AND pm.model_name = 'SureColor P400'
);
GO

-- ============================================
-- NOTE: The following models were not mapped to images:
--   - HP LaserJet Pro M404dn
--   - HP LaserJet Pro M428fdw
--   - HP DesignJet T650
--   - Canon imageCLASS LBP6030w
--   - Canon imageCLASS MF445dw
--   - Canon imagePROGRAF iPF771
--   - Brother HL-L2350DW
--   - Brother MFC-L2710DW
--   - Brother HL-L3270CDW
-- ============================================

-- Step 2: Verify the changes
-- Uncomment the following to verify:
-- SELECT TOP 20
--     pm.model_id,
--     b.brand_name,
--     pm.model_name,
--     pm.image_2d_url,
--     pm.image_3d_url
-- FROM printer_model pm
-- JOIN brand b ON pm.brand_id = b.brand_id
-- WHERE pm.image_2d_url IS NOT NULL
-- ORDER BY b.brand_name, pm.model_name;
-- GO

-- ============================================
-- Migration completed successfully
-- ============================================
-- Note: This migration updates existing URLs. For new data generation,
-- use the updated generate.py script which automatically generates Supabase URLs.
